# Generated by Django 3.2.13 on 2022-06-19 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_liked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_liked', to='food.food')),
            ],
        ),
    ]
